stages:
  - build
  - test
  - deploy

include:
  - base-line.yml

.backend:
  extends: 
    - .base-line
  variables:
    RULES_CHANGES_PATH: /../backend/**/*

build-job:
  stage: build
  extends: 
    - .backend
  script:
    - echo "build phase"

test-job:
  stage: build
  extends: 
    - .backend
  script:
    - echo "test phase"
