stages:
  - build
  - test
  - deploy

include:
  - base-line.yml

.frontend:
  extends: 
    - .base-line
  variables:
    RULES_CHANGES_PATH: /../frontend/**/*

build-job:
  stage: build
  extends: 
    - .frontend
  script:
    - echo "build phase"

test-job:
  stage: build
  extends: 
    - base-line.yml
  script:
    - echo "test phase"