stages:
  - build
  - test
  - deploy

.backend:
  extends: 
    - base-line.yml
  variables:
    RULES_CHANGES_PATH: /../frontend/**/*

build-job:
  stage: build
  extends: 
    - base-line.yml
  script:
    - echo "build phase"

test-job:
  stage: build
  extends: 
    - base-line.yml
  script:
    - echo "test phase"