spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
          facebook:
            client-id: ${FACEBOOK_CLIENTID}
            client-secret: ${FACEBOOK_CLIENTSECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org:
      springframework:
        security: DEBUG

#app variable
frontend:
  url: ${FRONTEND_URL}

access-token:
  private: ./access-refresh-token-keys/access-token-private.key
  public: ./access-refresh-token-keys/access-token-public.key

refresh-token:
  private: ./access-refresh-token-keys/refresh-token-private.key
  public: ./access-refresh-token-keys/refresh-token-public.key

api-route: api/v1
